apiVersion: v1
kind: Services
metadata:
  name: javawebapp-svc-
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8888
      name: http
    - name: "https"
      port: 443
      targetPort: 8888
      protocol: "TCP"
  selector:
    app: javawebapp
    version: "BUILD_NUMBER"
